// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Canonical taxonomy catalog, synced from the backend catalog in
// job-tracker-nextjs/src/lib/nlp-extract.ts. Regenerate with:
//
//   npm run sync:catalog
//
// taxonomyCatalog.test.ts verifies CATALOG_HASH against this content and
// compares against the backend source when that repo is available. This
// module must stay dependency-free: it is bundled into the injected
// content script.

export interface TaxonomyEntry {
  readonly canonical: string;
  readonly aliases?: readonly string[];
}

/** SHA-256 of the canonical JSON of the four catalogs below. */
export const CATALOG_HASH =
  '9f9eba8219f45b56586e8137d2d135e126abee81dcd812c43836fd2d6606471c';

/** Human-readable catalog version; changes exactly when content changes. */
export const CATALOG_VERSION = 'sha256:9f9eba8219f4';

// Skills: languages, practices, methods, and capabilities.
export const SKILLS: readonly TaxonomyEntry[] = [
  { canonical: 'TypeScript' },
  { canonical: 'JavaScript' },
  { canonical: 'Python' },
  { canonical: 'Kotlin' },
  { canonical: 'Swift' },
  { canonical: 'Scala' },
  { canonical: 'Haskell' },
  { canonical: 'Clojure' },
  { canonical: 'Elixir' },
  { canonical: 'Erlang' },
  { canonical: 'PowerShell' },
  { canonical: 'Ruby' },
  { canonical: 'Rust' },
  { canonical: 'Java' },
  { canonical: 'Go' },
  { canonical: 'PHP' },
  { canonical: 'C#' },
  { canonical: 'C++' },
  { canonical: 'Bash / Shell Scripting', aliases: ['Bash', 'Shell Scripting'] },
  { canonical: 'HTML5' },
  { canonical: 'CSS3' },
  { canonical: 'Sass / SCSS', aliases: ['SCSS', 'Sass'] },
  { canonical: 'CSS Modules' },
  { canonical: 'SQL' },
  { canonical: 'Assembly' },
  { canonical: 'Accessibility (WCAG)', aliases: ['WCAG'] },
  { canonical: 'Progressive Web Apps', aliases: ['PWA'] },
  { canonical: 'Service Workers' },
  { canonical: 'WebSockets' },
  { canonical: 'WebRTC' },
  {
    canonical: 'OAuth 2.0 / OpenID Connect',
    aliases: ['OAuth 2.0', 'OpenID Connect', 'OAuth'],
  },
  { canonical: 'REST API Design', aliases: ['REST API'] },
  { canonical: 'WebSocket Server' },
  { canonical: 'GraphQL' },
  { canonical: 'gRPC' },
  { canonical: 'JWT' },
  { canonical: 'Database Design' },
  { canonical: 'Data Modeling' },
  { canonical: 'Query Optimization' },
  { canonical: 'Infrastructure as Code', aliases: ['IaC'] },
  { canonical: 'Site Reliability Engineering', aliases: ['SRE'] },
  { canonical: 'Serverless / Lambda', aliases: ['Serverless', 'Lambda'] },
  { canonical: 'Load Balancing' },
  { canonical: 'Observability' },
  { canonical: 'CDN' },
  { canonical: 'CI/CD' },
  { canonical: 'Natural Language Processing', aliases: ['NLP'] },
  { canonical: 'Machine Learning', aliases: ['ML'] },
  { canonical: 'Deep Learning' },
  { canonical: 'Computer Vision' },
  { canonical: 'Feature Engineering' },
  { canonical: 'Model Evaluation' },
  { canonical: 'Data Warehousing' },
  { canonical: 'ETL Pipelines', aliases: ['ETL'] },
  { canonical: 'Vector Databases' },
  { canonical: 'iOS Development', aliases: ['iOS'] },
  { canonical: 'Android Development', aliases: ['Android'] },
  { canonical: 'App Store Deployment' },
  { canonical: 'Test-Driven Development', aliases: ['TDD'] },
  { canonical: 'End-to-End Testing', aliases: ['E2E Testing'] },
  { canonical: 'Integration Testing' },
  { canonical: 'Unit Testing' },
  { canonical: 'Load Testing' },
  { canonical: 'Performance Testing' },
  { canonical: 'Mock / Stub / Spy' },
  { canonical: 'Zero Trust Architecture', aliases: ['Zero Trust'] },
  { canonical: 'Static Analysis (SAST)', aliases: ['SAST'] },
  { canonical: 'Application Security', aliases: ['AppSec'] },
  { canonical: 'Dependency Scanning' },
  { canonical: 'Secret Management' },
  { canonical: 'Penetration Testing', aliases: ['Pen Testing'] },
  { canonical: 'SOC 2 Compliance', aliases: ['SOC 2'] },
  { canonical: 'OWASP Top 10', aliases: ['OWASP'] },
  { canonical: 'Encryption' },
  { canonical: 'Security Clearance — TS/SCI', aliases: ['TS/SCI'] },
  { canonical: 'Security Clearance — Secret' },
  { canonical: 'Concurrency & Parallelism', aliases: ['Concurrency'] },
  { canonical: 'Networking (TCP/IP)', aliases: ['TCP/IP'] },
  { canonical: 'Operating Systems' },
  { canonical: 'Memory Management' },
  { canonical: 'Embedded Systems' },
  { canonical: 'Protocol Buffers', aliases: ['Protobuf'] },
  { canonical: 'Message Queues' },
  { canonical: 'Compiler Design' },
  { canonical: 'FPGA' },
  { canonical: 'Event-Driven Architecture', aliases: ['Event-Driven'] },
  { canonical: 'Domain-Driven Design', aliases: ['DDD'] },
  { canonical: 'CQRS / Event Sourcing', aliases: ['CQRS'] },
  { canonical: 'High Availability Design', aliases: ['High Availability'] },
  { canonical: 'Performance Optimization' },
  { canonical: 'Distributed Systems' },
  { canonical: 'Clean Architecture' },
  { canonical: 'Design Patterns' },
  { canonical: 'Caching Strategies', aliases: ['Caching'] },
  { canonical: 'Microservices' },
  { canonical: 'System Design' },
  { canonical: 'API Gateway' },
  { canonical: 'Semantic Versioning', aliases: ['SemVer'] },
  { canonical: 'Code Review' },
  { canonical: 'Monorepo' },
  { canonical: 'Cross-Functional Collaboration' },
  { canonical: 'Stakeholder Communication' },
  { canonical: 'Agile / Scrum', aliases: ['Scrum', 'Agile'] },
  { canonical: 'Technical Writing' },
  { canonical: 'Problem Solving' },
  { canonical: 'Kanban' },
  { canonical: 'Mentoring' },
  { canonical: 'Debugging' },
];

// Software: named tools, products, platforms, frameworks, and services.
export const SOFTWARE: readonly TaxonomyEntry[] = [
  { canonical: 'Jira' },
  { canonical: 'Confluence' },
  { canonical: 'Slack' },
  { canonical: 'Bitbucket' },
  { canonical: 'VS Code' },
  { canonical: 'IntelliJ' },
  { canonical: 'Figma' },
  { canonical: 'Notion' },
  { canonical: 'Splunk' },
  { canonical: 'Tableau' },
  { canonical: 'Git' },
  { canonical: 'GitHub' },
  { canonical: 'GitLab' },
  { canonical: 'React' },
  { canonical: 'React Native' },
  { canonical: 'Angular' },
  { canonical: 'Vue.js', aliases: ['Vue'] },
  { canonical: 'Svelte' },
  { canonical: 'SvelteKit' },
  { canonical: 'Next.js' },
  { canonical: 'Nuxt.js' },
  { canonical: 'Remix' },
  { canonical: 'Redux' },
  { canonical: 'Zustand' },
  { canonical: 'Recoil' },
  { canonical: 'MobX' },
  { canonical: 'TanStack Query' },
  { canonical: 'TanStack Table' },
  { canonical: 'Framer Motion' },
  { canonical: 'Tailwind CSS', aliases: ['Tailwind'] },
  { canonical: 'Three.js' },
  { canonical: 'D3.js', aliases: ['D3'] },
  { canonical: 'Recharts' },
  { canonical: 'Chart.js' },
  { canonical: 'Webpack' },
  { canonical: 'Rollup' },
  { canonical: 'Vite' },
  { canonical: 'esbuild' },
  { canonical: 'Node.js' },
  { canonical: 'Express.js', aliases: ['Express'] },
  { canonical: 'Fastify' },
  { canonical: 'NestJS' },
  { canonical: 'Django' },
  { canonical: 'Flask' },
  { canonical: 'FastAPI' },
  { canonical: 'Ruby on Rails', aliases: ['Rails'] },
  { canonical: 'Laravel' },
  { canonical: 'Spring Boot', aliases: ['Spring'] },
  { canonical: 'ASP.NET Core', aliases: ['ASP.NET'] },
  { canonical: 'tRPC' },
  { canonical: 'Prisma' },
  { canonical: 'Drizzle ORM' },
  { canonical: 'SQLAlchemy' },
  { canonical: 'Hibernate' },
  { canonical: 'PostgreSQL', aliases: ['Postgres'] },
  { canonical: 'MySQL' },
  { canonical: 'SQLite' },
  { canonical: 'MongoDB' },
  { canonical: 'Redis' },
  { canonical: 'Elasticsearch' },
  { canonical: 'DynamoDB' },
  { canonical: 'Cassandra' },
  { canonical: 'Neo4j' },
  { canonical: 'CockroachDB' },
  { canonical: 'Supabase' },
  { canonical: 'PlanetScale' },
  { canonical: 'AWS', aliases: ['Amazon Web Services'] },
  { canonical: 'GCP', aliases: ['Google Cloud Platform', 'Google Cloud'] },
  { canonical: 'Azure' },
  { canonical: 'Cloudflare' },
  { canonical: 'Vercel' },
  { canonical: 'Netlify' },
  { canonical: 'Heroku' },
  { canonical: 'Railway' },
  { canonical: 'Docker' },
  { canonical: 'Kubernetes', aliases: ['k8s'] },
  { canonical: 'Helm' },
  { canonical: 'Terraform' },
  { canonical: 'Ansible' },
  { canonical: 'Pulumi' },
  { canonical: 'GitHub Actions' },
  { canonical: 'GitLab CI/CD', aliases: ['GitLab CI'] },
  { canonical: 'CircleCI' },
  { canonical: 'Jenkins' },
  { canonical: 'Nginx' },
  { canonical: 'Apache' },
  { canonical: 'Linux' },
  { canonical: 'Prometheus' },
  { canonical: 'Grafana' },
  { canonical: 'Datadog' },
  { canonical: 'OpenTelemetry' },
  { canonical: 'PyTorch' },
  { canonical: 'TensorFlow' },
  { canonical: 'Keras' },
  { canonical: 'scikit-learn', aliases: ['sklearn'] },
  { canonical: 'Hugging Face Transformers', aliases: ['Hugging Face'] },
  { canonical: 'LangChain' },
  { canonical: 'OpenAI API', aliases: ['OpenAI'] },
  { canonical: 'Pandas' },
  { canonical: 'NumPy' },
  { canonical: 'Matplotlib' },
  { canonical: 'Jupyter Notebooks', aliases: ['Jupyter'] },
  { canonical: 'MLflow' },
  { canonical: 'Spark' },
  { canonical: 'Kafka' },
  { canonical: 'RabbitMQ' },
  { canonical: 'Airflow' },
  { canonical: 'dbt' },
  { canonical: 'Snowflake' },
  { canonical: 'BigQuery' },
  { canonical: 'Flutter' },
  { canonical: 'Expo' },
  { canonical: 'SwiftUI' },
  { canonical: 'Jetpack Compose' },
  { canonical: 'Playwright' },
  { canonical: 'Cypress' },
  { canonical: 'Selenium' },
  { canonical: 'Vitest' },
  { canonical: 'Jest' },
  { canonical: 'PyTest' },
  { canonical: 'JUnit' },
];

// Certifications: named credentials and licenses only.
export const CERTIFICATIONS: readonly TaxonomyEntry[] = [
  {
    canonical: 'AWS Certified Solutions Architect',
    aliases: ['AWS Solutions Architect'],
  },
  { canonical: 'AWS Certified Developer' },
  { canonical: 'AWS Certified SysOps Administrator' },
  { canonical: 'AWS Certified DevOps Engineer' },
  { canonical: 'AWS Certified Cloud Practitioner' },
  { canonical: 'AWS Certified Security' },
  { canonical: 'AWS Certified' },
  {
    canonical: 'Microsoft Certified: Azure Fundamentals',
    aliases: ['Azure Fundamentals', 'AZ-900'],
  },
  {
    canonical: 'Microsoft Certified: Azure Administrator',
    aliases: ['Azure Administrator', 'AZ-104'],
  },
  {
    canonical: 'Microsoft Certified: Azure Solutions Architect',
    aliases: ['Azure Solutions Architect', 'AZ-305'],
  },
  {
    canonical: 'Microsoft Certified: Azure DevOps Engineer',
    aliases: ['Azure DevOps Engineer', 'AZ-400'],
  },
  { canonical: 'Azure Certified' },
  {
    canonical: 'Google Cloud Professional Cloud Architect',
    aliases: ['Professional Cloud Architect'],
  },
  {
    canonical: 'Google Cloud Associate Cloud Engineer',
    aliases: ['Associate Cloud Engineer'],
  },
  {
    canonical: 'Google Cloud Professional Data Engineer',
    aliases: ['Professional Data Engineer'],
  },
  { canonical: 'GCP Certified', aliases: ['Google Cloud Certified'] },
  { canonical: 'CompTIA Security+', aliases: ['Security+'] },
  { canonical: 'CompTIA Network+', aliases: ['Network+'] },
  { canonical: 'CompTIA A+' },
  { canonical: 'CompTIA' },
  { canonical: 'CISSP' },
  { canonical: 'CISM' },
  { canonical: 'CEH', aliases: ['Certified Ethical Hacker'] },
  { canonical: 'PMP', aliases: ['Project Management Professional'] },
  { canonical: 'CPA' },
  {
    canonical: 'Certified Kubernetes Administrator (CKA)',
    aliases: [
      'CKA',
      'Certified Kubernetes Administrator',
      'Kubernetes Administrator',
    ],
  },
  {
    canonical: 'Certified Kubernetes Application Developer (CKAD)',
    aliases: ['CKAD', 'Certified Kubernetes Application Developer'],
  },
  {
    canonical: 'HashiCorp Terraform Associate',
    aliases: ['Terraform Associate'],
  },
];

// Keywords: contextual labels, not a structured taxonomy. Overlap with
// skills (e.g. "microservices") is intentional and allowed.
export const KEYWORDS: readonly string[] = [
  'remote',
  'hybrid',
  'on-site',
  'full-stack',
  'full stack',
  'backend',
  'front-end',
  'frontend',
  'machine learning',
  'data engineering',
  'DevOps',
  'platform engineering',
  'distributed systems',
  'microservices',
  'startup',
  'series A',
  'series B',
  'series C',
  'executive',
  'senior',
  'lead',
  'staff',
  'principal',
  'entry level',
  'junior',
  'mid-level',
];
