// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Canonical taxonomy catalog, synced from the backend catalog in
// job-tracker-nextjs/src/lib/nlp-extract.ts. Regenerate with:
//
//   npm run sync:catalog
//
// taxonomyCatalog.test.ts verifies CATALOG_HASH against this content and
// compares against the backend source when that repo is available. This
// module must stay dependency-free: it is bundled into the injected
// content script.

export interface TaxonomyEntry {
  readonly canonical: string;
  readonly aliases?: readonly string[];
}

/** SHA-256 of the canonical JSON of the four catalogs below. */
export const CATALOG_HASH =
  '318e8d91adc90304c40dc82f8c9362cd178abba55fa153545274536906b18d29';

/** Human-readable catalog version; changes exactly when content changes. */
export const CATALOG_VERSION = 'sha256:318e8d91adc9';

// Skills: languages, practices, methods, and capabilities.
export const SKILLS: readonly TaxonomyEntry[] = [
  { canonical: 'TypeScript' },
  { canonical: 'JavaScript' },
  { canonical: 'Python' },
  { canonical: 'Kotlin' },
  { canonical: 'Swift' },
  { canonical: 'Scala' },
  { canonical: 'Haskell' },
  { canonical: 'Clojure' },
  { canonical: 'Elixir' },
  { canonical: 'Erlang' },
  { canonical: 'PowerShell' },
  { canonical: 'Ruby' },
  { canonical: 'Rust' },
  { canonical: 'Java' },
  { canonical: 'Go' },
  { canonical: 'PHP' },
  { canonical: 'C#' },
  { canonical: 'C++' },
  { canonical: 'Bash / Shell Scripting', aliases: ['Bash', 'Shell Scripting'] },
  { canonical: 'HTML5' },
  { canonical: 'CSS3' },
  { canonical: 'Sass / SCSS', aliases: ['SCSS', 'Sass'] },
  { canonical: 'CSS Modules' },
  { canonical: 'SQL' },
  { canonical: 'Assembly' },
  { canonical: 'Accessibility (WCAG)', aliases: ['WCAG'] },
  { canonical: 'Progressive Web Apps', aliases: ['PWA'] },
  { canonical: 'Service Workers' },
  { canonical: 'WebSockets' },
  { canonical: 'WebRTC' },
  {
    canonical: 'OAuth 2.0 / OpenID Connect',
    aliases: ['OAuth 2.0', 'OpenID Connect', 'OAuth'],
  },
  { canonical: 'REST API Design', aliases: ['REST API'] },
  { canonical: 'WebSocket Server' },
  { canonical: 'GraphQL' },
  { canonical: 'gRPC' },
  { canonical: 'JWT' },
  { canonical: 'Database Design' },
  { canonical: 'Data Modeling' },
  { canonical: 'Query Optimization' },
  { canonical: 'Infrastructure as Code', aliases: ['IaC'] },
  { canonical: 'Site Reliability Engineering', aliases: ['SRE'] },
  { canonical: 'Serverless / Lambda', aliases: ['Serverless', 'Lambda'] },
  { canonical: 'Load Balancing' },
  { canonical: 'Observability' },
  { canonical: 'CDN' },
  { canonical: 'CI/CD' },
  { canonical: 'Natural Language Processing', aliases: ['NLP'] },
  { canonical: 'Machine Learning', aliases: ['ML'] },
  { canonical: 'Deep Learning' },
  { canonical: 'Computer Vision' },
  { canonical: 'Feature Engineering' },
  { canonical: 'Model Evaluation' },
  { canonical: 'Generative AI', aliases: ['GenAI'] },
  {
    canonical: 'Large Language Models',
    aliases: ['LLMs', 'Large Language Model'],
  },
  { canonical: 'Prompt Engineering' },
  { canonical: 'Retrieval-Augmented Generation', aliases: ['RAG'] },
  { canonical: 'MLOps' },
  { canonical: 'Statistical Analysis' },
  { canonical: 'Data Visualization' },
  { canonical: 'Data Governance' },
  { canonical: 'Data Warehousing' },
  { canonical: 'ETL Pipelines', aliases: ['ETL'] },
  { canonical: 'Vector Databases' },
  { canonical: 'iOS Development', aliases: ['iOS'] },
  { canonical: 'Android Development', aliases: ['Android'] },
  { canonical: 'App Store Deployment' },
  { canonical: 'Test-Driven Development', aliases: ['TDD'] },
  { canonical: 'End-to-End Testing', aliases: ['E2E Testing'] },
  { canonical: 'Integration Testing' },
  { canonical: 'Unit Testing' },
  { canonical: 'Load Testing' },
  { canonical: 'Performance Testing' },
  { canonical: 'Mock / Stub / Spy' },
  { canonical: 'Zero Trust Architecture', aliases: ['Zero Trust'] },
  { canonical: 'Static Analysis (SAST)', aliases: ['SAST'] },
  { canonical: 'Application Security', aliases: ['AppSec'] },
  { canonical: 'Dependency Scanning' },
  { canonical: 'Secret Management' },
  { canonical: 'Penetration Testing', aliases: ['Pen Testing'] },
  { canonical: 'SOC 2 Compliance', aliases: ['SOC 2'] },
  { canonical: 'OWASP Top 10', aliases: ['OWASP'] },
  { canonical: 'Encryption' },
  { canonical: 'Incident Response' },
  { canonical: 'Threat Modeling' },
  { canonical: 'Vulnerability Management' },
  { canonical: 'Identity and Access Management', aliases: ['IAM'] },
  { canonical: 'Security Information and Event Management', aliases: ['SIEM'] },
  { canonical: 'Governance, Risk, and Compliance', aliases: ['GRC'] },
  { canonical: 'Security Clearance — TS/SCI', aliases: ['TS/SCI'] },
  { canonical: 'Security Clearance — Secret' },
  { canonical: 'Concurrency & Parallelism', aliases: ['Concurrency'] },
  { canonical: 'Networking (TCP/IP)', aliases: ['TCP/IP'] },
  { canonical: 'Operating Systems' },
  { canonical: 'Memory Management' },
  { canonical: 'Embedded Systems' },
  { canonical: 'Protocol Buffers', aliases: ['Protobuf'] },
  { canonical: 'Message Queues' },
  { canonical: 'DNS' },
  { canonical: 'HTTP' },
  { canonical: 'Network Security' },
  { canonical: 'Compiler Design' },
  { canonical: 'FPGA' },
  { canonical: 'Event-Driven Architecture', aliases: ['Event-Driven'] },
  { canonical: 'Domain-Driven Design', aliases: ['DDD'] },
  { canonical: 'CQRS / Event Sourcing', aliases: ['CQRS'] },
  { canonical: 'High Availability Design', aliases: ['High Availability'] },
  { canonical: 'Performance Optimization' },
  { canonical: 'Distributed Systems' },
  { canonical: 'Clean Architecture' },
  { canonical: 'Design Patterns' },
  { canonical: 'Caching Strategies', aliases: ['Caching'] },
  { canonical: 'Microservices' },
  { canonical: 'System Design' },
  { canonical: 'API Gateway' },
  { canonical: 'Object-Oriented Programming', aliases: ['OOP'] },
  { canonical: 'Functional Programming' },
  { canonical: 'SOLID Principles', aliases: ['SOLID'] },
  { canonical: 'Semantic Versioning', aliases: ['SemVer'] },
  { canonical: 'Code Review' },
  { canonical: 'Monorepo' },
  { canonical: 'Cross-Functional Collaboration' },
  { canonical: 'Stakeholder Communication' },
  { canonical: 'Agile / Scrum', aliases: ['Scrum', 'Agile'] },
  { canonical: 'Project Management' },
  { canonical: 'Product Management' },
  { canonical: 'Program Management' },
  { canonical: 'Change Management' },
  { canonical: 'Requirements Gathering' },
  { canonical: 'Business Analysis' },
  { canonical: 'Data Analysis' },
  { canonical: 'Technical Writing' },
  { canonical: 'Problem Solving' },
  { canonical: 'Kanban' },
  { canonical: 'Mentoring' },
  { canonical: 'Debugging' },
];

// Software: named tools, products, platforms, frameworks, and services.
export const SOFTWARE: readonly TaxonomyEntry[] = [
  { canonical: 'Jira' },
  { canonical: 'Confluence' },
  { canonical: 'Slack' },
  { canonical: 'Bitbucket' },
  { canonical: 'VS Code' },
  { canonical: 'IntelliJ' },
  { canonical: 'Figma' },
  { canonical: 'Notion' },
  { canonical: 'Microsoft Teams', aliases: ['MS Teams'] },
  { canonical: 'Microsoft 365', aliases: ['Office 365'] },
  { canonical: 'ServiceNow' },
  { canonical: 'Salesforce' },
  { canonical: 'Asana' },
  { canonical: 'Trello' },
  { canonical: 'Miro' },
  { canonical: 'Splunk' },
  { canonical: 'Tableau' },
  { canonical: 'Git' },
  { canonical: 'GitHub' },
  { canonical: 'GitLab' },
  { canonical: 'React' },
  { canonical: 'React Native' },
  { canonical: 'Angular' },
  { canonical: 'Vue.js', aliases: ['Vue'] },
  { canonical: 'Svelte' },
  { canonical: 'SvelteKit' },
  { canonical: 'Next.js' },
  { canonical: 'Nuxt.js' },
  { canonical: 'Remix' },
  { canonical: 'Redux' },
  { canonical: 'Zustand' },
  { canonical: 'Recoil' },
  { canonical: 'MobX' },
  { canonical: 'TanStack Query' },
  { canonical: 'TanStack Table' },
  { canonical: 'Framer Motion' },
  { canonical: 'Tailwind CSS', aliases: ['Tailwind'] },
  { canonical: 'Three.js' },
  { canonical: 'D3.js', aliases: ['D3'] },
  { canonical: 'Recharts' },
  { canonical: 'Chart.js' },
  { canonical: 'Webpack' },
  { canonical: 'Rollup' },
  { canonical: 'Vite' },
  { canonical: 'esbuild' },
  { canonical: 'Storybook' },
  { canonical: 'Material UI', aliases: ['MUI'] },
  { canonical: 'Bootstrap' },
  { canonical: 'Node.js' },
  { canonical: 'Express.js', aliases: ['Express'] },
  { canonical: 'Fastify' },
  { canonical: 'NestJS' },
  { canonical: 'Django' },
  { canonical: 'Flask' },
  { canonical: 'FastAPI' },
  { canonical: 'Ruby on Rails', aliases: ['Rails'] },
  { canonical: 'Laravel' },
  { canonical: 'Spring Boot', aliases: ['Spring'] },
  { canonical: 'ASP.NET Core', aliases: ['ASP.NET'] },
  { canonical: 'tRPC' },
  { canonical: 'Go Fiber' },
  { canonical: 'Gin Framework' },
  { canonical: 'Phoenix Framework' },
  { canonical: 'Prisma' },
  { canonical: 'Drizzle ORM' },
  { canonical: 'SQLAlchemy' },
  { canonical: 'Hibernate' },
  { canonical: 'Entity Framework' },
  { canonical: 'Sequelize' },
  { canonical: 'PostgreSQL', aliases: ['Postgres'] },
  { canonical: 'MySQL' },
  { canonical: 'SQLite' },
  { canonical: 'MongoDB' },
  { canonical: 'Redis' },
  { canonical: 'Elasticsearch' },
  { canonical: 'DynamoDB' },
  { canonical: 'Cassandra' },
  { canonical: 'Neo4j' },
  { canonical: 'CockroachDB' },
  { canonical: 'Supabase' },
  { canonical: 'PlanetScale' },
  { canonical: 'Oracle Database', aliases: ['Oracle DB'] },
  { canonical: 'Microsoft SQL Server', aliases: ['SQL Server'] },
  { canonical: 'MariaDB' },
  { canonical: 'Amazon Redshift', aliases: ['Redshift'] },
  { canonical: 'Pinecone' },
  { canonical: 'Weaviate' },
  { canonical: 'AWS', aliases: ['Amazon Web Services'] },
  { canonical: 'GCP', aliases: ['Google Cloud Platform', 'Google Cloud'] },
  { canonical: 'Azure' },
  { canonical: 'Cloudflare' },
  { canonical: 'Vercel' },
  { canonical: 'Netlify' },
  { canonical: 'Heroku' },
  { canonical: 'Railway' },
  { canonical: 'DigitalOcean' },
  { canonical: 'OpenShift' },
  { canonical: 'VMware' },
  { canonical: 'Docker' },
  { canonical: 'Kubernetes', aliases: ['k8s'] },
  { canonical: 'Helm' },
  { canonical: 'Terraform' },
  { canonical: 'Ansible' },
  { canonical: 'Pulumi' },
  { canonical: 'GitHub Actions' },
  { canonical: 'GitLab CI/CD', aliases: ['GitLab CI'] },
  { canonical: 'CircleCI' },
  { canonical: 'Jenkins' },
  { canonical: 'Nginx' },
  { canonical: 'Apache' },
  { canonical: 'Linux' },
  { canonical: 'Argo CD', aliases: ['ArgoCD'] },
  { canonical: 'Tekton' },
  { canonical: 'HashiCorp Packer' },
  { canonical: 'HashiCorp Vault' },
  { canonical: 'Prometheus' },
  { canonical: 'Grafana' },
  { canonical: 'Datadog' },
  { canonical: 'OpenTelemetry' },
  { canonical: 'New Relic' },
  { canonical: 'Sentry' },
  { canonical: 'PagerDuty' },
  { canonical: 'Dynatrace' },
  { canonical: 'PyTorch' },
  { canonical: 'TensorFlow' },
  { canonical: 'Keras' },
  { canonical: 'scikit-learn', aliases: ['sklearn'] },
  { canonical: 'Hugging Face Transformers', aliases: ['Hugging Face'] },
  { canonical: 'LangChain' },
  { canonical: 'OpenAI API', aliases: ['OpenAI'] },
  { canonical: 'Pandas' },
  { canonical: 'NumPy' },
  { canonical: 'Matplotlib' },
  { canonical: 'Jupyter Notebooks', aliases: ['Jupyter'] },
  { canonical: 'MLflow' },
  { canonical: 'Spark' },
  { canonical: 'Kafka' },
  { canonical: 'RabbitMQ' },
  { canonical: 'Airflow' },
  { canonical: 'dbt' },
  { canonical: 'Snowflake' },
  { canonical: 'BigQuery' },
  { canonical: 'Databricks' },
  { canonical: 'Flink' },
  { canonical: 'Hadoop' },
  { canonical: 'Looker' },
  { canonical: 'Power BI' },
  { canonical: 'Flutter' },
  { canonical: 'Expo' },
  { canonical: 'SwiftUI' },
  { canonical: 'Jetpack Compose' },
  { canonical: 'Playwright' },
  { canonical: 'Cypress' },
  { canonical: 'Selenium' },
  { canonical: 'Vitest' },
  { canonical: 'Jest' },
  { canonical: 'PyTest' },
  { canonical: 'JUnit' },
  { canonical: 'Postman' },
  { canonical: 'k6' },
  { canonical: 'Gatling' },
];

// Certifications: named credentials and licenses only.
export const CERTIFICATIONS: readonly TaxonomyEntry[] = [
  {
    canonical: 'AWS Certified Solutions Architect',
    aliases: ['AWS Solutions Architect'],
  },
  { canonical: 'AWS Certified Developer' },
  { canonical: 'AWS Certified SysOps Administrator' },
  { canonical: 'AWS Certified DevOps Engineer' },
  { canonical: 'AWS Certified Cloud Practitioner' },
  { canonical: 'AWS Certified Security' },
  { canonical: 'AWS Certified Machine Learning Engineer' },
  { canonical: 'AWS Certified Data Engineer' },
  { canonical: 'AWS Certified' },
  {
    canonical: 'Microsoft Certified: Azure Fundamentals',
    aliases: ['Azure Fundamentals', 'AZ-900'],
  },
  {
    canonical: 'Microsoft Certified: Azure Administrator',
    aliases: ['Azure Administrator', 'AZ-104'],
  },
  {
    canonical: 'Microsoft Certified: Azure Solutions Architect',
    aliases: ['Azure Solutions Architect', 'AZ-305'],
  },
  {
    canonical: 'Microsoft Certified: Azure DevOps Engineer',
    aliases: ['Azure DevOps Engineer', 'AZ-400'],
  },
  {
    canonical: 'Microsoft Certified: Azure Security Engineer',
    aliases: ['Azure Security Engineer', 'AZ-500'],
  },
  {
    canonical: 'Microsoft Certified: Azure Data Engineer',
    aliases: ['Azure Data Engineer', 'DP-203'],
  },
  {
    canonical: 'Microsoft Certified: Azure AI Engineer',
    aliases: ['Azure AI Engineer', 'AI-102'],
  },
  { canonical: 'Azure Certified' },
  {
    canonical: 'Google Cloud Professional Cloud Architect',
    aliases: ['Professional Cloud Architect'],
  },
  {
    canonical: 'Google Cloud Associate Cloud Engineer',
    aliases: ['Associate Cloud Engineer'],
  },
  {
    canonical: 'Google Cloud Professional Data Engineer',
    aliases: ['Professional Data Engineer'],
  },
  {
    canonical: 'Google Cloud Professional Cloud Developer',
    aliases: ['Professional Cloud Developer'],
  },
  {
    canonical: 'Google Cloud Professional Cloud Security Engineer',
    aliases: ['Professional Cloud Security Engineer'],
  },
  { canonical: 'GCP Certified', aliases: ['Google Cloud Certified'] },
  { canonical: 'CompTIA Security+', aliases: ['Security+'] },
  { canonical: 'CompTIA Network+', aliases: ['Network+'] },
  { canonical: 'CompTIA Cloud+', aliases: ['Cloud+'] },
  { canonical: 'CompTIA Linux+', aliases: ['Linux+'] },
  { canonical: 'CompTIA CySA+', aliases: ['CySA+'] },
  { canonical: 'CompTIA A+' },
  { canonical: 'CompTIA' },
  { canonical: 'CISSP' },
  { canonical: 'CISM' },
  { canonical: 'CCSP', aliases: ['Certified Cloud Security Professional'] },
  { canonical: 'OSCP', aliases: ['Offensive Security Certified Professional'] },
  { canonical: 'GIAC Security Essentials', aliases: ['GSEC'] },
  { canonical: 'CEH', aliases: ['Certified Ethical Hacker'] },
  { canonical: 'PMP', aliases: ['Project Management Professional'] },
  { canonical: 'Certified ScrumMaster' },
  { canonical: 'Professional Scrum Master' },
  { canonical: 'ITIL Foundation' },
  { canonical: 'Six Sigma Green Belt' },
  { canonical: 'Six Sigma Black Belt' },
  { canonical: 'CPA' },
  {
    canonical: 'Certified Kubernetes Administrator (CKA)',
    aliases: [
      'CKA',
      'Certified Kubernetes Administrator',
      'Kubernetes Administrator',
    ],
  },
  {
    canonical: 'Certified Kubernetes Application Developer (CKAD)',
    aliases: ['CKAD', 'Certified Kubernetes Application Developer'],
  },
  {
    canonical: 'HashiCorp Terraform Associate',
    aliases: ['Terraform Associate'],
  },
  { canonical: 'Cisco Certified Network Associate', aliases: ['CCNA'] },
  { canonical: 'Cisco Certified Network Professional', aliases: ['CCNP'] },
  { canonical: 'Red Hat Certified System Administrator', aliases: ['RHCSA'] },
  { canonical: 'Red Hat Certified Engineer', aliases: ['RHCE'] },
];

// Keywords: contextual labels, not a structured taxonomy. Overlap with
// skills (e.g. "microservices") is intentional and allowed.
export const KEYWORDS: readonly TaxonomyEntry[] = [
  { canonical: 'remote' },
  { canonical: 'hybrid' },
  { canonical: 'on-site', aliases: ['onsite'] },
  { canonical: 'full-stack', aliases: ['full stack'] },
  { canonical: 'backend' },
  { canonical: 'frontend', aliases: ['front-end'] },
  { canonical: 'mobile' },
  { canonical: 'machine learning' },
  { canonical: 'data engineering' },
  { canonical: 'data science' },
  { canonical: 'artificial intelligence' },
  { canonical: 'generative AI' },
  { canonical: 'DevOps' },
  { canonical: 'platform engineering' },
  { canonical: 'distributed systems' },
  { canonical: 'microservices' },
  { canonical: 'cloud-native', aliases: ['cloud native'] },
  { canonical: 'cybersecurity' },
  { canonical: 'fintech' },
  { canonical: 'healthtech' },
  { canonical: 'e-commerce', aliases: ['ecommerce'] },
  { canonical: 'B2B' },
  { canonical: 'B2C' },
  { canonical: 'SaaS' },
  { canonical: 'startup' },
  { canonical: 'series A' },
  { canonical: 'series B' },
  { canonical: 'series C' },
  { canonical: 'executive' },
  { canonical: 'senior' },
  { canonical: 'lead' },
  { canonical: 'staff' },
  { canonical: 'principal' },
  { canonical: 'entry level', aliases: ['entry-level'] },
  { canonical: 'junior' },
  { canonical: 'mid-level', aliases: ['mid level'] },
  { canonical: 'contract' },
  { canonical: 'contract-to-hire', aliases: ['contract to hire'] },
  { canonical: 'part-time', aliases: ['part time'] },
  { canonical: 'full-time', aliases: ['full time'] },
  { canonical: 'visa sponsorship' },
  { canonical: 'no sponsorship', aliases: ['no visa sponsorship'] },
  { canonical: 'equity' },
  { canonical: 'bonus' },
  { canonical: 'clearance required' },
];
